targets:
  $default:
    builders:
      riverpod_generator:
        options:
          # Configuration Riverpod
          riverpod_generator: true
      freezed:
        options:
          # Configuration Freezed
          union_key: type
          union_value_case: pascal
